DROP DATABASE IF EXISTS ohirugohan;
CREATE DATABASE ohirugohan;

use ohirugohan;

CREATE TABLE META (
    Id        INTEGER UNSIGNED PRIMARY KEY,
    Title     VARCHAR(128),
    Suffix    VARCHAR(4),
    Category  INTEGER UNSIGNED,
    IsDelete  ENUM('y', 'n') DEFAULT 'n', 
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE STORAGE (
    Id   INTEGER UNSIGNED PRIMARY KEY,
    Name VARCHAR(64)
) ENGINE=InnoDB;

CREATE TABLE CATEGORY (
    Id   INTEGER UNSIGNED PRIMARY KEY,
    Name VARCHAR(64)
) ENGINE=InnoDB;
